blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/ArchetypicalSoftware/vdk-flux/tree/main/docs
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/ArchetypicalSoftware/vdk-flux/discussions
    about: Ask questions and discuss ideas
  - name: VDK Template
    url: https://github.com/ArchetypicalSoftware/VDK-Template
    about: For issues with the VDK CLI tool
